-   repo: git@github.com:hootsuite/pre-commit-php.git
    sha: 1.2.0
    hooks:
    -   id: php-lint
    -   id: php-unit
-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: end-of-file-fixer
